//! `seldon rebuild` (WP-032, SPEC-ENGINE §3): `outputs/REBUILD.md` on a copy
//! of `fixtures/logbook/` is golden (`tests/golden/REBUILD.md`,
//! `SELDON_BLESS=1` rewrites it), every listed package traces to a ledger
//! event, a second run writes nothing, user text outside the fence stays,
//! and the autocommit happens only on a change. Always through
//! `common::Env` (temp home, `SELDON_TEST_GUARD`), never the real XDG dirs.

mod common;

use std::path::{Path, PathBuf};

use serde_json::{Value, json};

use common::{Env, Snapper, copy_dir, fixture_logbook, json, read, stderr, stdout};

/// The sample index's clock (`fixtures/index.sample.json`).
const NOW: &str = "2026-10-01T17:05:12+02:00";
const HEADER: &str = "<!-- generated by seldon; do not edit -->";

const OLLAMA: &str = "01M3VNFTF8EVHWFFZ687N14Q0C"; // open, crisis
const FIREFOX: &str = "01M3SXBQVR7AW8PJQC1YXDCQ14"; // leader of the 09-30 group

fn fixture_copy(env: &Env) -> PathBuf {
    let lb = env.tmp.path().join("logbook");
    copy_dir(&fixture_logbook(), &lb);
    lb
}

/// `seldon --logbook <lb> --json args…` at `now`; asserts `code`.
fn run_at(env: &Env, lb: &Path, now: &str, args: &[&str], code: i32) -> Value {
    let mut all = vec!["--logbook", lb.to_str().unwrap(), "--json"];
    all.extend_from_slice(args);
    let out = env.at(now, &all);
    assert_eq!(
        out.status.code(),
        Some(code),
        "{args:?}: {}{}",
        stdout(&out),
        stderr(&out)
    );
    json(&out)
}

fn rebuild(env: &Env, lb: &Path) -> Value {
    run_at(env, lb, NOW, &["rebuild"], 0)
}

fn doc(lb: &Path) -> String {
    read(&lb.join("outputs/REBUILD.md"))
}

/// The lines of one `## ` section (heading excluded).
fn section<'a>(text: &'a str, heading: &str) -> Vec<&'a str> {
    let start = text
        .find(&format!("\n## {heading}\n"))
        .unwrap_or_else(|| panic!("no section {heading}"));
    let body = &text[start + heading.len() + 5..];
    let end = body.find("\n## ").unwrap_or(body.len());
    body[..end].lines().collect()
}

/// The last inline-code span of a line (the event id).
fn last_code(line: &str) -> &str {
    let end = line.rfind('`').unwrap();
    let start = line[..end].rfind('`').unwrap();
    &line[start + 1..end]
}

#[test]
fn the_fixture_document_is_golden_and_traces_every_package() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    // the pre-logbook packages come from the dossier's `packages.explicit`
    // (WP-035), written from shimmed read-only queries
    env.query_shims();
    run_at(&env, &lb, NOW, &["dossier", "--section", "packages"], 0);
    let out = rebuild(&env, &lb);
    assert_eq!(
        out["sections"],
        json!({"packages": 4, "deviations": 5, "plugins": 3, "units": 2, "open": 4}),
        "{out}"
    );
    assert_eq!(out["files"], json!(["outputs/REBUILD.md"]));
    assert_eq!(
        out["path"].as_str().map(PathBuf::from),
        Some(lb.join("outputs/REBUILD.md"))
    );
    assert_eq!(out["git"]["committed"], json!(false), "no repository");

    let text = doc(&lb);
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/REBUILD.md");
    if std::env::var_os("SELDON_BLESS").is_some() {
        std::fs::write(&path, &text).unwrap();
    }
    let golden = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("{} missing; run with SELDON_BLESS=1", path.display()));
    assert_eq!(text, golden, "{} differs", path.display());
    assert!(text.starts_with(&format!("{HEADER}\n<!-- seldon:begin rebuild -->\n")));
    assert!(text.ends_with("<!-- seldon:end -->\n"));

    // English headings, the seven sections in order
    let headings: Vec<&str> = text.lines().filter(|l| l.starts_with("## ")).collect();
    assert_eq!(
        headings,
        [
            "## 1. Base",
            "## 2. Packages",
            "## 3. Deviations",
            "## 4. Plugins",
            "## 5. Theme",
            "## 6. User units",
            "## 7. Open questions"
        ]
    );
    // prose in the logbook language (de)
    assert!(text.contains("Installiere Omarchy und führe dann `omarchy update` aus"));

    assert_eq!(packages_trace(&lb, &text), 4);
    // 11 packages predate the logbook: 5 are the user's, 6 Omarchy's
    assert_eq!(before_trace(&lb, &text), 5);
}

/// Asserts that the "Before the logbook" group of section 2 lists every
/// `pre-logbook` package of class `user` of the dossier's
/// `packages.explicit` fence, each under the command of its origin, and
/// nothing else, and that one line counts the `omarchy-base` ones (WP-036);
/// returns the number of listed packages.
fn before_trace(lb: &Path, text: &str) -> usize {
    let dossier = read(&lb.join("system/packages.md"));
    let pre: Vec<&str> = dossier
        .lines()
        .filter(|l| l.ends_with(" · pre-logbook"))
        .collect();
    let base = pre
        .iter()
        .filter(|l| l.contains(" · omarchy-base · "))
        .count();
    assert!(base > 0, "the fixture has Omarchy's packages");
    let expected: Vec<(String, &str)> = pre
        .iter()
        .filter(|l| l.contains(" · user · "))
        .map(|l| {
            let mut parts = l.trim_start_matches("- ").split(" · ");
            let name = parts.next().unwrap().to_string();
            let cmd = match parts.next().unwrap() {
                "aur" => "omarchy pkg aur add",
                _ => "omarchy pkg add",
            };
            (name, cmd)
        })
        .collect();
    let packages = section(text, "2. Packages").join("\n");
    let start = packages
        .find("### Before the logbook\n")
        .expect("a Before the logbook group");
    let group = &packages[start..];
    let group = &group[..group[1..].find("\n### ").map_or(group.len(), |i| i + 1)];
    let base_line = format!("{base} weitere bringt Omarchy 4.0.7-1 mit (Klasse `omarchy-base`).");
    assert_eq!(
        group
            .lines()
            .filter(|l| l.contains("omarchy-base"))
            .collect::<Vec<_>>(),
        [base_line.as_str()],
        "{group}"
    );
    let block = &group[group.find("```sh\n").unwrap() + 6..];
    let block = &block[..block.find("```").unwrap()];
    let mut listed: Vec<(String, &str)> = Vec::new();
    let mut cmd = "";
    for line in block.lines() {
        let mut words = line.trim_end_matches(" \\").trim();
        for prefix in ["omarchy pkg aur add", "omarchy pkg add"] {
            if let Some(rest) = words.strip_prefix(prefix) {
                cmd = prefix;
                words = rest;
                break;
            }
        }
        listed.extend(words.split_whitespace().map(|w| (w.to_string(), cmd)));
    }
    listed.sort();
    let mut expected = expected;
    expected.sort();
    assert_eq!(listed, expected);
    listed.len()
}

/// Asserts that every package line of section 2 names an explicit
/// install event of that package (`omarchy pkg add` or `omarchy pkg aur
/// add`); returns the number of package lines.
fn packages_trace(lb: &Path, text: &str) -> usize {
    let ledger = common::ledger(lb);
    let packages: Vec<&str> = section(text, "2. Packages")
        .into_iter()
        .filter(|l| l.starts_with("- `omarchy pkg"))
        .collect();
    for line in &packages {
        let id = last_code(line);
        let event = ledger
            .iter()
            .find(|e| e["id"] == id)
            .unwrap_or_else(|| panic!("{line}: {id} is not a ledger event"));
        assert_eq!(event["source"], "pacman", "{line}");
        assert_eq!(event["kind"], "install", "{line}");
        assert_eq!(event["explicit"], true, "{line}");
        let name = event["subject"].as_str().unwrap();
        assert!(
            line.starts_with(&format!("- `omarchy pkg add {name}`"))
                || line.starts_with(&format!("- `omarchy pkg aur add {name}`")),
            "{line}"
        );
    }
    packages.len()
}

#[test]
fn a_second_run_writes_nothing_and_user_text_stays() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    let has_git = env.has_git;
    if has_git {
        for args in [
            &["init", "-q"][..],
            &["-c", "user.name=t", "-c", "user.email=t@t", "add", "-A"],
            &[
                "-c",
                "user.name=t",
                "-c",
                "user.email=t@t",
                "commit",
                "-qm",
                "fixture",
            ],
        ] {
            let out = env.git(&lb, args);
            assert!(out.status.success(), "git {args:?}: {}", stderr(&out));
        }
    }
    let git_log = || stdout(&env.git(&lb, &["log", "--format=%s"]));

    let first = rebuild(&env, &lb);
    assert_eq!(first["files"], json!(["outputs/REBUILD.md"]));
    if has_git {
        assert_eq!(first["git"]["committed"], json!(true), "{first}");
        assert_eq!(git_log().lines().next(), Some("seldon: rebuild"));
    }
    let text = doc(&lb);

    // again, later: no file, no commit, same bytes
    let again = run_at(&env, &lb, "2026-10-02T08:00:00+02:00", &["rebuild"], 0);
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(again["git"]["committed"], json!(false));
    assert_eq!(again["sections"], first["sections"]);
    assert_eq!(doc(&lb), text);
    if has_git {
        assert_eq!(git_log().matches("seldon: rebuild").count(), 1);
    }

    // the user writes around the fence; a change rewrites only the fence
    let edited = text.replacen(
        "<!-- seldon:begin rebuild -->",
        "Meine Notiz oben.\n\n<!-- seldon:begin rebuild -->",
        1,
    ) + "\n## Eigene Schritte\nYubikey einrichten.\n";
    std::fs::write(lb.join("outputs/REBUILD.md"), &edited).unwrap();
    let unchanged = rebuild(&env, &lb);
    assert_eq!(
        unchanged["files"],
        json!([]),
        "user text alone is no change"
    );
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", OLLAMA, "--", "Nur ausprobiert"],
        0,
    );
    let changed = rebuild(&env, &lb);
    assert_eq!(changed["files"], json!(["outputs/REBUILD.md"]));
    let text = doc(&lb);
    assert!(text.starts_with(&format!(
        "{HEADER}\nMeine Notiz oben.\n\n<!-- seldon:begin rebuild -->\n"
    )));
    assert!(
        text.ends_with("<!-- seldon:end -->\n\n## Eigene Schritte\nYubikey einrichten.\n"),
        "{text}"
    );
    assert_eq!(text.matches("seldon:begin rebuild").count(), 1);
    if has_git {
        // drift dismiss committed itself; rebuild once more
        assert_eq!(git_log().lines().next(), Some("seldon: rebuild"));
        assert_eq!(git_log().matches("seldon: rebuild").count(), 2);
    }
}

#[test]
fn resolutions_move_items_between_sections() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", OLLAMA, "--", "Nur ausprobiert"],
        0,
    );
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "explain", FIREFOX, "--", "Routine-Update"],
        0,
    );
    let out = rebuild(&env, &lb);
    // ollama left the packages, the firefox group and ollama left the open
    // questions; the unit file of ollama is still open
    assert_eq!(out["sections"]["packages"], 3, "{out}");
    assert_eq!(out["sections"]["open"], 2, "{out}");
    let text = doc(&lb);
    let packages = section(&text, "2. Packages").join("\n");
    assert!(!packages.contains("ollama"), "{packages}");
    let open = section(&text, "7. Open questions").join("\n");
    assert!(!open.contains(FIREFOX), "{open}");
    assert!(
        open.contains(&format!(
            "### Deliberately not reproduced\nBewusst verworfen; nicht wieder einrichten.\n\n- theme theme-set `kanagawa` — Nur ausprobiert. · `01M30363YR87Y4YKAVFT0SPZPX`\n- pacman install `ollama` — Nur ausprobiert · `{OLLAMA}`"
        )),
        "{open}"
    );
}

/// Appends raw ledger lines (fixture key order) to `ledger/2026-10.jsonl`.
fn append(lb: &Path, lines: &[Value]) {
    let path = lb.join("ledger/2026-10.jsonl");
    let mut text = read(&path);
    for l in lines {
        text.push_str(&serde_json::to_string(l).unwrap());
        text.push('\n');
    }
    std::fs::write(path, text).unwrap();
}

fn pacman(id: &str, ts: &str, kind: &str, subject: &str, command: Option<&str>) -> Value {
    let mut meta = json!({ "version": "1.0-1" });
    if let Some(c) = command {
        meta = json!({ "command": c, "version": "1.0-1" });
    }
    json!({
        "id": id, "ts": ts, "source": "pacman", "kind": kind, "subject": subject,
        "detail": "1.0-1", "actor": "system", "zone": "red", "explicit": true,
        "txId": format!("tx-{id}"), "meta": meta
    })
}

#[test]
fn aur_unknown_and_removed_packages_in_english() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    let toml = lb.join(".seldon/logbook.toml");
    std::fs::write(
        &toml,
        read(&toml).replace("language = \"de\"", "language = \"en\""),
    )
    .unwrap();
    append(
        &lb,
        &[
            pacman(
                "01M3W0000000000000000AAR01",
                "2026-10-01T17:10:00+02:00",
                "install",
                "brave-bin",
                Some(
                    "pacman -U --noconfirm --config /etc/pacman.conf -- /home/u/.cache/yay/brave-bin/brave-bin-1.80.1-1-x86_64.pkg.tar.zst",
                ),
            ),
            pacman(
                "01M3W0000000000000000XNK01",
                "2026-10-01T17:11:00+02:00",
                "install",
                "mystery",
                None,
            ),
            pacman(
                "01M3W0000000000000000REM01",
                "2026-10-01T17:12:00+02:00",
                "remove",
                "btop",
                Some("pacman -Rns btop"),
            ),
        ],
    );
    let out = rebuild(&env, &lb);
    // btop removed; brave-bin and mystery added (both open drift)
    assert_eq!(out["sections"]["packages"], 5, "{out}");
    let text = doc(&lb);
    let packages = section(&text, "2. Packages").join("\n");
    assert!(!packages.contains("btop"), "{packages}");
    assert!(
        packages.contains(
            "- `omarchy pkg aur add brave-bin` — 1.0-1 · **open**, see 7 · `01M3W0000000000000000AAR01`"
        ),
        "{packages}"
    );
    assert!(
        packages.contains(
            "- `omarchy pkg add mystery` (repository unknown; from the AUR: `omarchy pkg aur add mystery`) — 1.0-1 · **open**, see 7 · `01M3W0000000000000000XNK01`"
        ),
        "{packages}"
    );
    assert!(packages.contains(
        "\nAll repository packages at once (open ones left out): `omarchy pkg add tailscale zed`"
    ));
    assert!(text.contains(
        "- Install Omarchy, then run `omarchy update` until at least this version runs."
    ));
    assert!(text.contains("\n## 3. Deviations\nFiles that differ from the Omarchy default."));
    // the AUR line traces like the others
    assert_eq!(packages_trace(&lb, &text), 5);
}

fn english_fixture(env: &Env) -> PathBuf {
    let lb = fixture_copy(env);
    let toml = lb.join(".seldon/logbook.toml");
    std::fs::write(
        &toml,
        read(&toml).replace("language = \"de\"", "language = \"en\""),
    )
    .unwrap();
    lb
}

fn config(id: &str, ts: &str, kind: &str, subject: &str) -> Value {
    let (detail, meta) = match kind {
        "config-remove" => (
            "sha256 c0243ca5 → —",
            json!({ "hashFrom": "c0".repeat(32) }),
        ),
        _ => ("sha256 — → c0243ca5", json!({ "hashTo": "c0".repeat(32) })),
    };
    json!({
        "id": id, "ts": ts, "source": "config", "kind": kind, "subject": subject,
        "detail": detail, "actor": "system", "zone": "red", "meta": meta
    })
}

#[test]
fn a_dismissed_transaction_counts_every_member_and_units_show_drop_ins_and_removals() {
    let env = Env::new(Snapper::Missing);
    let lb = english_fixture(&env);
    let foo = "01M3W00000000000000000XP01";
    let mut dep = pacman(
        "01M3W00000000000000000DP01",
        "2026-10-01T17:13:00+02:00",
        "install",
        "libfoo",
        Some("pacman -S foo"),
    );
    dep["explicit"] = json!(false);
    dep["txId"] = json!("tx-foo");
    let mut explicit = pacman(
        foo,
        "2026-10-01T17:13:00+02:00",
        "install",
        "foo",
        Some("pacman -S foo"),
    );
    explicit["txId"] = json!("tx-foo");
    append(
        &lb,
        &[
            dep,
            explicit,
            // a unit file from before the logbook, removed
            config(
                "01M3W00000000000000000CR01",
                "2026-10-01T17:14:00+02:00",
                "config-remove",
                "~/.config/systemd/user/old.service",
            ),
            config(
                "01M3W00000000000000000DR01",
                "2026-10-01T17:15:00+02:00",
                "config-add",
                "~/.config/systemd/user/ollama.service.d/override.conf",
            ),
        ],
    );
    let dismissed = run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", foo, "--", "Only a test"],
        0,
    );
    assert_eq!(dismissed["resolved"], 2, "{dismissed}");
    let out = rebuild(&env, &lb);
    let text = doc(&lb);

    // the dismissed transaction: once, with both members counted
    let open = section(&text, "7. Open questions").join("\n");
    assert!(
        open.contains(&format!(
            "- pacman install `foo` · 2 events in this transaction — Only a test · `{foo}`"
        )),
        "{open}"
    );
    assert!(!open.contains("libfoo"), "{open}");
    assert!(
        !section(&text, "2. Packages").join("\n").contains("`foo`"),
        "a dismissed package is not reproduced"
    );

    // ollama.service, its drop-in, the removed unit, tailscaled
    assert_eq!(out["sections"]["units"], 4, "{out}");
    let units = section(&text, "6. User units").join("\n");
    assert!(
        units.contains(
            "- `~/.config/systemd/user/old.service` — remove this file, then `systemctl --user daemon-reload` · **open**, see 7 · `01M3W00000000000000000CR01`"
        ),
        "{units}"
    );
    assert!(
        units.contains(
            "- `~/.config/systemd/user/ollama.service.d/override.conf` (drop-in for `ollama.service`) — restore the file, then `systemctl --user enable --now ollama.service` · **open**, see 7 · `01M3W00000000000000000DR01`"
        ),
        "{units}"
    );
}

#[test]
fn an_empty_logbook_says_none_everywhere() {
    let env = Env::new(Snapper::Missing);
    let lb = env.init_logbook();
    let out = env.at(NOW, &["--json", "--no-commit", "rebuild"]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let out = json(&out);
    assert_eq!(
        out["sections"],
        json!({"packages": 0, "deviations": 0, "plugins": 0, "units": 0, "open": 0})
    );
    let text = doc(&lb);
    assert!(text.contains("## 2. Packages\n"));
    for heading in ["4. Plugins", "6. User units", "7. Open questions"] {
        assert!(
            section(&text, heading).contains(&"- none"),
            "{heading}: {text}"
        );
    }
}

#[test]
fn without_a_logbook_it_exits_3() {
    let env = Env::new(Snapper::Missing);
    let missing = env.tmp.path().join("nowhere");
    let out = env.at(
        NOW,
        &["--logbook", missing.to_str().unwrap(), "--json", "rebuild"],
    );
    assert_eq!(out.status.code(), Some(3), "{}", stdout(&out));
    assert!(!missing.join("outputs").exists());
}

/// Made-up names with shell syntax, a leading `-` and a quote; each
/// carries `tag` (so a command that holds one is found) and ends in `end`.
fn odd(tag: &str, end: &str) -> Vec<String> {
    vec![
        format!("x;{tag}1{end}"),
        format!("x$({tag}2){end}"),
        format!("x`{tag}3`{end}"),
        format!("x${{IFS}}{tag}4{end}"),
        format!("x|{tag}5{end}"),
        format!("x&&{tag}6{end}"),
        format!("-{tag}7{end}"),
        format!("x'{tag}8{end}"),
    ]
}

/// The inline code spans of a line (CommonMark: a run of n backticks is
/// closed by the next run of exactly n; one space each side is trimmed).
fn code_spans(line: &str) -> Vec<&str> {
    let b = line.as_bytes();
    let run = |i: usize| b[i..].iter().take_while(|&&c| c == b'`').count();
    let mut out = Vec::new();
    let mut i = 0;
    while i < b.len() {
        if b[i] != b'`' {
            i += 1;
            continue;
        }
        let n = run(i);
        let mut j = i + n;
        let mut close = None;
        while j < b.len() {
            if b[j] == b'`' {
                let m = run(j);
                if m == n {
                    close = Some(j);
                    break;
                }
                j += m;
            } else {
                j += 1;
            }
        }
        let Some(j) = close else {
            i += n;
            continue;
        };
        let c = &line[i + n..j];
        let c = match c.strip_prefix(' ').and_then(|c| c.strip_suffix(' ')) {
            Some(inner) if !inner.trim().is_empty() => inner,
            _ => c,
        };
        out.push(c);
        i = j + n;
    }
    out
}

/// Every command of the document: the lines of its `sh` blocks and the
/// code spans that start with a program the guide runs.
fn commands(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut in_block = false;
    for line in text.lines() {
        if in_block {
            if line == "```" {
                in_block = false;
            } else {
                out.push(line.to_string());
            }
        } else if line == "```sh" {
            in_block = true;
        } else {
            out.extend(
                code_spans(line)
                    .into_iter()
                    .filter(|c| {
                        ["omarchy ", "systemctl ", "sudo "]
                            .iter()
                            .any(|p| c.starts_with(p))
                    })
                    .map(String::from),
            );
        }
    }
    out
}

/// Asserts that no command holds `tag`.
fn no_command_holds(text: &str, tag: &str) {
    let hits: Vec<String> = commands(text)
        .into_iter()
        .filter(|c| c.contains(tag))
        .collect();
    assert!(hits.is_empty(), "{tag} in a command: {hits:?}\n{text}");
}

/// Asserts that a line lists `value` as not reproduced.
fn listed_as_not_reproduced(text: &str, value: &str) {
    assert!(
        text.lines()
            .any(|l| l.contains("not reproduced: invalid name") && code_spans(l).contains(&value)),
        "{value:?} is not listed as not reproduced\n{text}"
    );
}

/// Asserts that `out["warnings"]` names `value`.
fn warned(out: &Value, value: &str) {
    let needle = format!("{value:?} not reproduced: invalid name");
    assert!(
        out["warnings"]
            .as_array()
            .unwrap()
            .iter()
            .any(|w| w.as_str().unwrap().contains(&needle)),
        "no warning for {value:?}: {}",
        out["warnings"]
    );
}

/// Puts `rows` (Markdown lines) at the end of the fence `name` of `file`.
fn add_rows(lb: &Path, file: &str, name: &str, rows: &[String]) {
    let path = lb.join("system").join(file);
    let text = read(&path);
    let begin = format!("<!-- seldon:begin {name} -->\n");
    let start = text.find(&begin).unwrap() + begin.len();
    let end = start + text[start..].find("<!-- seldon:end -->").unwrap();
    let mut rows = rows.join("\n");
    rows.push('\n');
    std::fs::write(&path, format!("{}{rows}{}", &text[..end], &text[end..])).unwrap();
}

/// A ledger id for the n-th test event of a group (`tag`: four Crockford
/// letters).
fn test_id(tag: &str, n: usize) -> String {
    format!("01M3W000000000000000{tag}{n:02}")
}

#[test]
fn names_that_fail_their_check_never_reach_a_command() {
    let env = Env::new(Snapper::Missing);
    let lb = english_fixture(&env);
    let later = "2026-10-01T18:00:00+02:00";

    // packages fence: the user's pre-logbook packages
    let fence = odd("PKGFENCE", "");
    let mut rows = vec![
        "- firefox · repo · user · pre-logbook".to_string(),
        "- brave-bin · aur · user · pre-logbook".to_string(),
    ];
    for (i, v) in fence.iter().enumerate() {
        let origin = if i % 2 == 0 { "repo" } else { "aur" };
        rows.push(format!("- {v} · {origin} · user · pre-logbook"));
    }
    add_rows(&lb, "packages.md", "packages.explicit", &rows);

    // ledger subjects: explicit installs from the repositories, the AUR
    // and an unknown command, explained so the "all at once" lines see them
    let subjects = odd("PKGLEDGER", "");
    let commands_by_origin = [
        Some("pacman -S x"),
        Some("pacman -U --noconfirm -- /tmp/x-1-1-x86_64.pkg.tar.zst"),
        None,
    ];
    let events: Vec<Value> = subjects
        .iter()
        .enumerate()
        .map(|(i, v)| {
            pacman(
                &test_id("PACK", i),
                "2026-10-01T17:20:00+02:00",
                "install",
                v,
                commands_by_origin[i % 3],
            )
        })
        .collect();
    // user units with a unit file (config events) and enabled in the dossier
    let unit_paths = odd("USERPATH", ".service");
    let mut events = events;
    for (i, v) in unit_paths.iter().enumerate() {
        events.push(config(
            &test_id("CNFG", i),
            "2026-10-01T17:21:00+02:00",
            "config-add",
            &format!("~/.config/systemd/user/{v}"),
        ));
    }
    append(&lb, &events);
    for i in 0..subjects.len() {
        run_at(
            &env,
            &lb,
            later,
            &["drift", "explain", &test_id("PACK", i), "--", "test"],
            0,
        );
    }

    // services.enabled: user units without a file, system units
    let user_rows = odd("USERROW", ".service");
    let system_rows = odd("SYSROW", ".service");
    let mut rows: Vec<String> = Vec::new();
    for v in &unit_paths {
        rows.push(format!("| {v} | user | — |"));
    }
    for v in &user_rows {
        rows.push(format!("| {v} | user | [[C-2026-004]] |"));
    }
    for v in &system_rows {
        rows.push(format!("| {v} | system | [[C-2026-008]] |"));
    }
    add_rows(&lb, "services.md", "services.enabled", &rows);

    // plugins.list: clones of an odd source, first-party plugins disabled
    let clones = odd("PLUGCLONE", "");
    let first_party = odd("FIRSTPARTY", "");
    let mut rows: Vec<String> = Vec::new();
    for (i, v) in clones.iter().enumerate() {
        rows.push(format!("| user.clone{i} | yes | no | {v} |"));
    }
    for v in &first_party {
        rows.push(format!("| {v} | no | yes | — |"));
    }
    add_rows(&lb, "plugins.md", "plugins.list", &rows);

    // plugin-add events: odd URLs, odd ids to enable, a URL to quote
    let urls: Vec<String> = odd("PLUGURL", "")
        .into_iter()
        .map(|v| match v.starts_with('-') {
            true => v,
            false => format!("https://example.org/{v}"),
        })
        .collect();
    for (i, url) in urls.iter().enumerate() {
        let id = format!("io.example.url{i}");
        let meta = format!("url={url}");
        let args = [
            "event",
            "plugins",
            "plugin-add",
            "--subject",
            &id,
            "--meta",
            &meta,
        ];
        run_at(&env, &lb, later, &args, 0);
    }
    let ids = odd("PLUGID", "");
    for id in &ids {
        let args = [
            "event",
            "plugins",
            "plugin-add",
            "--subject",
            id,
            "--meta",
            "enabled=true",
        ];
        run_at(&env, &lb, later, &args, 0);
    }
    let tilde = "https://git.example.org/~someone/clock-plus";
    let meta = format!("url={tilde}");
    let args = [
        "event",
        "plugins",
        "plugin-add",
        "--subject",
        "io.example.tilde",
        "--meta",
        &meta,
        "--meta",
        "enabled=true",
    ];
    run_at(&env, &lb, later, &args, 0);

    let out = run_at(&env, &lb, later, &["rebuild"], 0);
    let text = doc(&lb);

    for tag in [
        "PKGFENCE",
        "PKGLEDGER",
        "USERPATH",
        "USERROW",
        "SYSROW",
        "PLUGCLONE",
        "FIRSTPARTY",
        "PLUGURL",
        "PLUGID",
    ] {
        no_command_holds(&text, tag);
    }
    // a `|` cannot be part of a table cell, so the table sinks never see
    // those values whole; everything else is listed and warned about
    let whole = |v: &&String| !v.contains('|');
    let unit_files: Vec<String> = unit_paths
        .iter()
        .filter(whole)
        .map(|v| format!("~/.config/systemd/user/{v}"))
        .collect();
    for v in fence
        .iter()
        .chain(&subjects)
        .chain(user_rows.iter().filter(whole))
        .chain(system_rows.iter().filter(whole))
        .chain(clones.iter().filter(whole))
        .chain(urls.iter())
        .chain(ids.iter())
    {
        warned(&out, v);
    }
    for v in fence
        .iter()
        .chain(&subjects)
        .chain(&unit_files)
        .chain(user_rows.iter().filter(whole))
        .chain(system_rows.iter().filter(whole))
        .chain(ids.iter())
    {
        listed_as_not_reproduced(&text, v);
    }
    // a plugin line names its id; the clone source or URL was the odd part
    let plugins = section(&text, "4. Plugins");
    for (i, v) in clones.iter().enumerate() {
        if v.contains('|') {
            continue;
        }
        let line = format!("- `user.clone{i}` — not reproduced: invalid name");
        assert!(plugins.contains(&line.as_str()), "{line}\n{text}");
    }
    for i in 0..urls.len() {
        let line = format!("- `io.example.url{i}` — not reproduced: invalid name");
        assert!(
            plugins.iter().any(|l| l.starts_with(&line)),
            "{line}\n{text}"
        );
    }
    let disabled = plugins
        .iter()
        .find(|l| l.starts_with("First-party plugins disabled here"))
        .unwrap();
    for v in first_party.iter().filter(whole) {
        warned(&out, v);
        let shown = code_spans(disabled);
        assert!(shown.contains(&v.as_str()), "{v:?}: {disabled}");
        assert!(
            disabled.contains(" (not reproduced: invalid name)"),
            "{disabled}"
        );
    }

    // valid names stay as they were; a URL with a `~` is quoted
    assert!(
        text.contains("```sh\nomarchy pkg add firefox\nomarchy pkg aur add brave-bin\n```\n"),
        "{text}"
    );
    assert!(
        text.contains(&format!(
            "- `io.example.tilde` — `omarchy plugin add '{tilde}'`, then `omarchy plugin enable io.example.tilde`"
        )),
        "{text}"
    );
    assert!(text.contains("\nAll repository packages at once (open ones left out): `omarchy pkg add btop tailscale zed`\n"), "{text}");
    assert!(
        text.contains("- `tailscaled.service` — `sudo systemctl enable --now tailscaled.service`")
    );
}

#[test]
fn a_theme_name_that_fails_its_check_is_not_set() {
    let env = Env::new(Snapper::Missing);
    let lb = english_fixture(&env);
    for (i, v) in odd("THEME", "").iter().enumerate() {
        let now = format!("2026-10-01T18:{i:02}:00+02:00");
        run_at(
            &env,
            &lb,
            &now,
            &["event", "theme", "theme-set", "--subject", v],
            0,
        );
        let out = run_at(&env, &lb, &now, &["rebuild"], 0);
        let text = doc(&lb);
        no_command_holds(&text, "THEME");
        listed_as_not_reproduced(&text, v);
        warned(&out, v);
        assert_eq!(
            section(&text, "5. Theme")
                .iter()
                .filter(|l| l.starts_with("- "))
                .count(),
            1,
            "{text}"
        );
    }
}

/// A made-up value that spans lines and holds a fence of its own.
fn multi_line(tag: &str) -> String {
    format!("n{tag}\n```sh\necho {tag}\n```")
}

#[test]
fn a_value_with_line_breaks_stays_inside_its_code_span() {
    let env = Env::new(Snapper::Missing);
    let lb = english_fixture(&env);
    add_rows(
        &lb,
        "packages.md",
        "packages.explicit",
        &["- firefox · repo · user · pre-logbook".to_string()],
    );
    let ts = "2026-10-01T17:20:00+02:00";
    let plugin = |id: &str, subject: &str, enabled: Option<bool>| {
        let mut meta = json!({ "version": "1.0" });
        if let Some(e) = enabled {
            meta["enabled"] = json!(e);
        }
        json!({
            "id": id, "ts": ts, "source": "plugins", "kind": "plugin-add",
            "subject": subject, "detail": "1.0", "actor": "system",
            "zone": "yellow", "meta": meta
        })
    };
    let dismissed = test_id("BRKS", 1);
    append(
        &lb,
        &[
            // §2 not reproduced, §7 open
            pacman(
                &test_id("BRKS", 0),
                ts,
                "install",
                &multi_line("PKG"),
                Some("pacman -S x"),
            ),
            // §7 dismissed
            pacman(
                &dismissed,
                ts,
                "install",
                &multi_line("DSM"),
                Some("pacman -S x"),
            ),
            // §4 a plugin line with a command, and one not reproduced
            plugin(&test_id("BRKS", 2), &multi_line("PLA"), None),
            plugin(&test_id("BRKS", 3), &multi_line("PLB"), Some(true)),
            // §5 not reproduced
            json!({
                "id": test_id("BRKS", 4), "ts": "2026-10-01T17:21:00+02:00",
                "source": "theme", "kind": "theme-set",
                "subject": multi_line("THM"), "detail": "x", "actor": "human",
                "zone": "yellow", "meta": {}
            }),
            // §6 a unit file (restore, then reload), §7 open
            config(
                &test_id("BRKS", 5),
                ts,
                "config-add",
                &format!("~/.config/systemd/user/{}.service", multi_line("UNT")),
            ),
        ],
    );
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", &dismissed, "--", "test"],
        0,
    );
    rebuild(&env, &lb);
    let text = doc(&lb);

    let openers = text.lines().filter(|l| l.starts_with("```sh")).count();
    assert_eq!(openers, 1, "only the Before the logbook block\n{text}");
    assert_eq!(
        text.lines()
            .filter(|l| l.trim_start().starts_with("```"))
            .count(),
        2,
        "{text}"
    );
    // every value is there, escaped, in its section
    let shown = |tag: &str| format!("n{tag}\\n```sh\\necho {tag}\\n```");
    for (heading, tags) in [
        ("2. Packages", &["PKG"][..]),
        ("4. Plugins", &["PLA", "PLB"]),
        ("5. Theme", &["THM"]),
        ("6. User units", &["UNT"]),
        (
            "7. Open questions",
            &["PKG", "UNT", "DSM", "THM", "PLA", "PLB"],
        ),
    ] {
        let body = section(&text, heading).join("\n");
        for tag in tags {
            assert!(body.contains(&shown(tag)), "{tag} in {heading}\n{text}");
        }
    }
    let not_reproduced = |tag: &str| {
        text.lines()
            .any(|l| l.contains(&shown(tag)) && l.contains("not reproduced: invalid name"))
    };
    for tag in ["PKG", "PLB", "THM"] {
        assert!(not_reproduced(tag), "{tag}\n{text}");
    }
}
