//! `seldon rebuild` (WP-032, SPEC-ENGINE §3): `outputs/REBUILD.md` on a copy
//! of `fixtures/logbook/` is golden (`tests/golden/REBUILD.md`,
//! `SELDON_BLESS=1` rewrites it), every listed package traces to a ledger
//! event, a second run writes nothing, user text outside the fence stays,
//! and the autocommit happens only on a change. Always through
//! `common::Env` (temp home, `SELDON_TEST_GUARD`), never the real XDG dirs.

mod common;

use std::path::{Path, PathBuf};

use serde_json::{Value, json};

use common::{Env, Snapper, copy_dir, fixture_logbook, json, read, stderr, stdout};

/// The sample index's clock (`fixtures/index.sample.json`).
const NOW: &str = "2026-10-01T17:05:12+02:00";
const HEADER: &str = "<!-- generated by seldon; do not edit -->";

const OLLAMA: &str = "01M3VNFTF8EVHWFFZ687N14Q0C"; // open, crisis
const FIREFOX: &str = "01M3SXBQVR7AW8PJQC1YXDCQ14"; // leader of the 09-30 group

fn fixture_copy(env: &Env) -> PathBuf {
    let lb = env.tmp.path().join("logbook");
    copy_dir(&fixture_logbook(), &lb);
    lb
}

/// `seldon --logbook <lb> --json args…` at `now`; asserts `code`.
fn run_at(env: &Env, lb: &Path, now: &str, args: &[&str], code: i32) -> Value {
    let mut all = vec!["--logbook", lb.to_str().unwrap(), "--json"];
    all.extend_from_slice(args);
    let out = env.at(now, &all);
    assert_eq!(
        out.status.code(),
        Some(code),
        "{args:?}: {}{}",
        stdout(&out),
        stderr(&out)
    );
    json(&out)
}

fn rebuild(env: &Env, lb: &Path) -> Value {
    run_at(env, lb, NOW, &["rebuild"], 0)
}

fn doc(lb: &Path) -> String {
    read(&lb.join("outputs/REBUILD.md"))
}

/// The lines of one `## ` section (heading excluded).
fn section<'a>(text: &'a str, heading: &str) -> Vec<&'a str> {
    let start = text
        .find(&format!("\n## {heading}\n"))
        .unwrap_or_else(|| panic!("no section {heading}"));
    let body = &text[start + heading.len() + 5..];
    let end = body.find("\n## ").unwrap_or(body.len());
    body[..end].lines().collect()
}

/// The last inline-code span of a line (the event id).
fn last_code(line: &str) -> &str {
    let end = line.rfind('`').unwrap();
    let start = line[..end].rfind('`').unwrap();
    &line[start + 1..end]
}

#[test]
fn the_fixture_document_is_golden_and_traces_every_package() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    let out = rebuild(&env, &lb);
    assert_eq!(
        out["sections"],
        json!({"packages": 4, "deviations": 5, "plugins": 3, "units": 2, "open": 4}),
        "{out}"
    );
    assert_eq!(out["files"], json!(["outputs/REBUILD.md"]));
    assert_eq!(
        out["path"].as_str().map(PathBuf::from),
        Some(lb.join("outputs/REBUILD.md"))
    );
    assert_eq!(out["git"]["committed"], json!(false), "no repository");

    let text = doc(&lb);
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/REBUILD.md");
    if std::env::var_os("SELDON_BLESS").is_some() {
        std::fs::write(&path, &text).unwrap();
    }
    let golden = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("{} missing; run with SELDON_BLESS=1", path.display()));
    assert_eq!(text, golden, "{} differs", path.display());
    assert!(text.starts_with(&format!("{HEADER}\n<!-- seldon:begin rebuild -->\n")));
    assert!(text.ends_with("<!-- seldon:end -->\n"));

    // English headings, the seven sections in order
    let headings: Vec<&str> = text.lines().filter(|l| l.starts_with("## ")).collect();
    assert_eq!(
        headings,
        [
            "## 1. Base",
            "## 2. Packages",
            "## 3. Deviations",
            "## 4. Plugins",
            "## 5. Theme",
            "## 6. User units",
            "## 7. Open questions"
        ]
    );
    // prose in the logbook language (de)
    assert!(text.contains("Installiere Omarchy und führe dann `omarchy update` aus"));

    // every listed package names an explicit, not removed install event
    let ledger = common::ledger(&lb);
    let packages: Vec<&str> = section(&text, "2. Packages")
        .into_iter()
        .filter(|l| l.starts_with("- `omarchy pkg"))
        .collect();
    assert_eq!(packages.len(), 4, "{packages:?}");
    for line in packages {
        let id = last_code(line);
        let event = ledger
            .iter()
            .find(|e| e["id"] == id)
            .unwrap_or_else(|| panic!("{line}: {id} is not a ledger event"));
        assert_eq!(event["source"], "pacman", "{line}");
        assert_eq!(event["kind"], "install", "{line}");
        assert_eq!(event["explicit"], true, "{line}");
        let name = event["subject"].as_str().unwrap();
        assert!(
            line.starts_with(&format!("- `omarchy pkg add {name}`")),
            "{line}"
        );
    }
}

#[test]
fn a_second_run_writes_nothing_and_user_text_stays() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    let has_git = env.has_git;
    if has_git {
        for args in [
            &["init", "-q"][..],
            &["-c", "user.name=t", "-c", "user.email=t@t", "add", "-A"],
            &[
                "-c",
                "user.name=t",
                "-c",
                "user.email=t@t",
                "commit",
                "-qm",
                "fixture",
            ],
        ] {
            let out = env.git(&lb, args);
            assert!(out.status.success(), "git {args:?}: {}", stderr(&out));
        }
    }
    let git_log = || stdout(&env.git(&lb, &["log", "--format=%s"]));

    let first = rebuild(&env, &lb);
    assert_eq!(first["files"], json!(["outputs/REBUILD.md"]));
    if has_git {
        assert_eq!(first["git"]["committed"], json!(true), "{first}");
        assert_eq!(git_log().lines().next(), Some("seldon: rebuild"));
    }
    let text = doc(&lb);

    // again, later: no file, no commit, same bytes
    let again = run_at(&env, &lb, "2026-10-02T08:00:00+02:00", &["rebuild"], 0);
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(again["git"]["committed"], json!(false));
    assert_eq!(again["sections"], first["sections"]);
    assert_eq!(doc(&lb), text);
    if has_git {
        assert_eq!(git_log().matches("seldon: rebuild").count(), 1);
    }

    // the user writes around the fence; a change rewrites only the fence
    let edited = text.replacen(
        "<!-- seldon:begin rebuild -->",
        "Meine Notiz oben.\n\n<!-- seldon:begin rebuild -->",
        1,
    ) + "\n## Eigene Schritte\nYubikey einrichten.\n";
    std::fs::write(lb.join("outputs/REBUILD.md"), &edited).unwrap();
    let unchanged = rebuild(&env, &lb);
    assert_eq!(
        unchanged["files"],
        json!([]),
        "user text alone is no change"
    );
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", OLLAMA, "--", "Nur ausprobiert"],
        0,
    );
    let changed = rebuild(&env, &lb);
    assert_eq!(changed["files"], json!(["outputs/REBUILD.md"]));
    let text = doc(&lb);
    assert!(text.starts_with(&format!(
        "{HEADER}\nMeine Notiz oben.\n\n<!-- seldon:begin rebuild -->\n"
    )));
    assert!(
        text.ends_with("<!-- seldon:end -->\n\n## Eigene Schritte\nYubikey einrichten.\n"),
        "{text}"
    );
    assert_eq!(text.matches("seldon:begin rebuild").count(), 1);
    if has_git {
        // drift dismiss committed itself; rebuild once more
        assert_eq!(git_log().lines().next(), Some("seldon: rebuild"));
        assert_eq!(git_log().matches("seldon: rebuild").count(), 2);
    }
}

#[test]
fn resolutions_move_items_between_sections() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "dismiss", OLLAMA, "--", "Nur ausprobiert"],
        0,
    );
    run_at(
        &env,
        &lb,
        NOW,
        &["drift", "explain", FIREFOX, "--", "Routine-Update"],
        0,
    );
    let out = rebuild(&env, &lb);
    // ollama left the packages, the firefox group and ollama left the open
    // questions; the unit file of ollama is still open
    assert_eq!(out["sections"]["packages"], 3, "{out}");
    assert_eq!(out["sections"]["open"], 2, "{out}");
    let text = doc(&lb);
    let packages = section(&text, "2. Packages").join("\n");
    assert!(!packages.contains("ollama"), "{packages}");
    let open = section(&text, "7. Open questions").join("\n");
    assert!(!open.contains(FIREFOX), "{open}");
    assert!(
        open.contains(&format!(
            "### Deliberately not reproduced\nBewusst verworfen; nicht wieder einrichten.\n\n- theme theme-set `kanagawa` — Nur ausprobiert. · `01M30363YR87Y4YKAVFT0SPZPX`\n- pacman install `ollama` — Nur ausprobiert · `{OLLAMA}`"
        )),
        "{open}"
    );
}

/// Appends raw ledger lines (fixture key order) to `ledger/2026-10.jsonl`.
fn append(lb: &Path, lines: &[Value]) {
    let path = lb.join("ledger/2026-10.jsonl");
    let mut text = read(&path);
    for l in lines {
        text.push_str(&serde_json::to_string(l).unwrap());
        text.push('\n');
    }
    std::fs::write(path, text).unwrap();
}

fn pacman(id: &str, ts: &str, kind: &str, subject: &str, command: Option<&str>) -> Value {
    let mut meta = json!({ "version": "1.0-1" });
    if let Some(c) = command {
        meta = json!({ "command": c, "version": "1.0-1" });
    }
    json!({
        "id": id, "ts": ts, "source": "pacman", "kind": kind, "subject": subject,
        "detail": "1.0-1", "actor": "system", "zone": "red", "explicit": true,
        "txId": format!("tx-{id}"), "meta": meta
    })
}

#[test]
fn aur_unknown_and_removed_packages_in_english() {
    let env = Env::new(Snapper::Missing);
    let lb = fixture_copy(&env);
    let toml = lb.join(".seldon/logbook.toml");
    std::fs::write(
        &toml,
        read(&toml).replace("language = \"de\"", "language = \"en\""),
    )
    .unwrap();
    append(
        &lb,
        &[
            pacman(
                "01M3W0000000000000000AAR01",
                "2026-10-01T17:10:00+02:00",
                "install",
                "brave-bin",
                Some(
                    "pacman -U --noconfirm --config /etc/pacman.conf -- /home/u/.cache/yay/brave-bin/brave-bin-1.80.1-1-x86_64.pkg.tar.zst",
                ),
            ),
            pacman(
                "01M3W0000000000000000XNK01",
                "2026-10-01T17:11:00+02:00",
                "install",
                "mystery",
                None,
            ),
            pacman(
                "01M3W0000000000000000REM01",
                "2026-10-01T17:12:00+02:00",
                "remove",
                "btop",
                Some("pacman -Rns btop"),
            ),
        ],
    );
    let out = rebuild(&env, &lb);
    // btop removed; brave-bin and mystery added (both open drift)
    assert_eq!(out["sections"]["packages"], 5, "{out}");
    let text = doc(&lb);
    let packages = section(&text, "2. Packages").join("\n");
    assert!(!packages.contains("btop"), "{packages}");
    assert!(
        packages.contains(
            "- `omarchy pkg aur add brave-bin` — 1.0-1 · **open**, see 7 · `01M3W0000000000000000AAR01`"
        ),
        "{packages}"
    );
    assert!(
        packages.contains(
            "- `omarchy pkg add mystery` (repository unknown; from the AUR: `omarchy pkg aur add mystery`) — 1.0-1 · **open**, see 7 · `01M3W0000000000000000XNK01`"
        ),
        "{packages}"
    );
    assert!(packages.contains(
        "\nAll repository packages at once (open ones left out): `omarchy pkg add tailscale zed`"
    ));
    assert!(text.contains(
        "- Install Omarchy, then run `omarchy update` until at least this version runs."
    ));
    assert!(text.contains("\n## 3. Deviations\nFiles that differ from the Omarchy default."));
}

#[test]
fn an_empty_logbook_says_none_everywhere() {
    let env = Env::new(Snapper::Missing);
    let lb = env.init_logbook();
    let out = env.at(NOW, &["--json", "--no-commit", "rebuild"]);
    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let out = json(&out);
    assert_eq!(
        out["sections"],
        json!({"packages": 0, "deviations": 0, "plugins": 0, "units": 0, "open": 0})
    );
    let text = doc(&lb);
    assert!(text.contains("## 2. Packages\n"));
    for heading in ["4. Plugins", "6. User units", "7. Open questions"] {
        assert!(
            section(&text, heading).contains(&"- none"),
            "{heading}: {text}"
        );
    }
}

#[test]
fn without_a_logbook_it_exits_3() {
    let env = Env::new(Snapper::Missing);
    let missing = env.tmp.path().join("nowhere");
    let out = env.at(
        NOW,
        &["--logbook", missing.to_str().unwrap(), "--json", "rebuild"],
    );
    assert_eq!(out.status.code(), Some(3), "{}", stdout(&out));
    assert!(!missing.join("outputs").exists());
}
