//! `seldon status` (WP-007): STATUS.md with the generated header, user
//! text outside the fence kept, prose in the logbook language, no rewrite
//! when nothing changed; and the index rebuilt by the writing commands
//! (CONTRACT.md rule 2). Everything runs in a temp home (common::Env).

mod common;

use std::path::Path;

use serde_json::{Value, json};

use common::{Env, Snapper, copy_dir, fixture_logbook, read};

const HEADER: &str = "<!-- generated by seldon; do not edit -->";
const NOW: &str = "2026-10-01T17:05:12+02:00";

fn index(env: &Env) -> Value {
    serde_json::from_str(&read(&env.home.join(".local/state/seldon/index.json"))).unwrap()
}

fn status(env: &Env, now: &str) -> Value {
    let out = env.at(now, &["status", "--json"]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}{}",
        common::stdout(&out),
        common::stderr(&out)
    );
    common::json(&out)
}

fn git_log(env: &Env, root: &Path) -> String {
    common::stdout(&env.git(root, &["log", "--format=%s"]))
}

#[test]
fn status_writes_status_md_and_keeps_user_text() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let path = root.join("STATUS.md");
    assert!(read(&path).contains("No status yet"), "the init template");

    let out = status(&env, NOW);
    assert_eq!(out["ok"], json!(true));
    assert_eq!(out["status"], json!("STATUS.md"));
    assert!(
        out["files"]
            .as_array()
            .unwrap()
            .contains(&json!("STATUS.md")),
        "{out}"
    );
    assert_eq!(out["summary"]["activeCases"], json!(0));
    let text = read(&path);
    assert!(text.starts_with(&format!("{HEADER}\n<!-- seldon:begin status -->\n")));
    assert!(text.contains("\n## Overview\n- Active cases: 0 · in verification: 0 · queued: 0\n"));
    assert!(text.contains("## Open drift\n- none\n"));
    assert!(!text.contains("No status yet"), "the template is replaced");
    common::assert_valid_index(&index(&env));

    // the user writes above and below the fence
    let edited = text.replacen(
        "<!-- seldon:begin status -->",
        "My intro.\n\n<!-- seldon:begin status -->",
        1,
    ) + "\n## My notes\nKeep this.\n";
    std::fs::write(&path, &edited).unwrap();
    // a case changes the generated part
    let new = env.at(
        NOW,
        &["plan", "new", "--zone", "red", "--risk", "R2", "--", "Zed"],
    );
    assert_eq!(new.status.code(), Some(0), "{}", common::stderr(&new));
    let out = status(&env, NOW);
    let text = read(&path);
    assert!(text.starts_with(&format!(
        "{HEADER}\nMy intro.\n\n<!-- seldon:begin status -->\n"
    )));
    assert!(
        text.ends_with("<!-- seldon:end -->\n\n## My notes\nKeep this.\n"),
        "{text}"
    );
    assert!(
        text.contains("## Queued\n- [[C-2026-001]] Zed — red/R2"),
        "{text}"
    );
    assert!(text.contains("queued: 1"));
    assert_eq!(out["summary"]["queuedCases"], json!(1));
    assert_eq!(text.matches("seldon:begin status").count(), 1);

    // nothing changed: nothing is written, nothing committed
    let again = status(&env, "2026-10-01T18:00:00+02:00");
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(again["git"]["committed"], json!(false));
    assert_eq!(read(&path), text);
    if env.has_git {
        let log = git_log(&env, &root);
        assert_eq!(log.lines().next(), Some("seldon: status"), "{log}");
        assert_eq!(log.matches("seldon: status").count(), 2, "{log}");
    }
}

#[test]
fn status_prose_follows_the_logbook_language() {
    let env = Env::new(Snapper::Missing);
    let lb = env.tmp.path().join("logbook");
    copy_dir(&fixture_logbook(), &lb);
    let out = env.at(
        NOW,
        &["--logbook", lb.to_str().unwrap(), "status", "--json"],
    );
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let json = common::json(&out);
    assert_eq!(json["summary"]["openDrift"], json!(4));
    assert_eq!(json["git"]["committed"], json!(false), "no repository");
    let text = read(&lb.join("STATUS.md"));
    let generated = "\
<!-- generated by seldon; do not edit -->
<!-- seldon:begin status -->
# Status — workstation-7f3a

Stand: 2026-10-01 · letztes Ereignis 17:00 · Omarchy 4.0.7-1 · Theme tokyo-night

## Overview
- Aktive Cases: 2 · in Prüfung: 1 · geplant: 3
- Offene Drift: 4, davon Krise: 2
- Ereignisse heute: 27 · letzte 7 Tage: 38

## Active cases
- [[C-2026-003]] Omarchy auf 4.0.7 aktualisieren — red/R2 — 4/5 Schritte — agent:claude-code
- [[C-2026-004]] Zed als zweiten Editor installieren — red/R2 — 2/4 Schritte — agent:claude-code

## In verification
- [[C-2026-008]] Tailscale für Fernzugriff einrichten — red/R2 — 3/4 Schritte

## Queued
- [[C-2026-005]] Theme-Wechsel auf Tokyo Night durchziehen (Zed, Neovim) — yellow/R1 — 0/4 Schritte
- [[C-2026-006]] Snapper-Retention auf 14 Tage — red/R2 — 0/3 Schritte
- [[C-2026-007]] Herdr-Orchestrator als Default-Agent registrieren — yellow/R1 — 0/5 Schritte

## Open drift
- 15:30 theme · theme-set `tokyo-night` kanagawa → tokyo-night · human · Vorschlag [[C-2026-005]]
- **Krise** 14:03 config · config-add `~/.config/systemd/user/ollama.service` · agent:codex
- **Krise** 14:02 pacman · install `ollama` 0.6.1-1 · agent:codex
- 2026-09-30 21:41 pacman · upgrade `firefox` 143.0.1-1 → 143.0.2-1 · 3 Ereignisse in dieser Transaktion
<!-- seldon:end -->
";
    assert_eq!(text, generated);
}

#[test]
fn a_degraded_collector_is_listed() {
    let env = Env::new(Snapper::NoPermissions);
    env.init_logbook();
    let out = env.at(NOW, &["capture", "--source", "snapper", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    status(&env, NOW);
    let root = env.tmp.path().join("logbook");
    let text = read(&root.join("STATUS.md"));
    assert!(
        text.contains("\n## Collectors\n- snapper: degraded — "),
        "{text}"
    );
    let ix = index(&env);
    let snapper = &ix["state"]["collectors"][1];
    assert_eq!(snapper["name"], json!("snapper"));
    assert_eq!(snapper["ok"], json!(false));
    assert!(
        snapper["message"]
            .as_str()
            .unwrap()
            .contains("No permissions")
    );
    assert!(snapper["lastRun"].is_string());
    assert_eq!(ix["state"]["lastCapture"], snapper["lastRun"]);
    assert_eq!(
        ix["state"]["collectors"][0]["lastRun"],
        json!(null),
        "pacman did not run"
    );
}

#[test]
fn writing_commands_rebuild_the_index() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let index_file = env.home.join(".local/state/seldon/index.json");
    assert!(!index_file.exists(), "init does not write the index");

    let log = env.at(NOW, &["log", "--", "Zed ausprobiert"]);
    assert_eq!(log.status.code(), Some(0), "{}", common::stderr(&log));
    assert!(common::stderr(&log).is_empty(), "{}", common::stderr(&log));
    let ix = index(&env);
    common::assert_valid_index(&ix);
    assert_eq!(ix["generatedAt"], json!(NOW));
    assert_eq!(ix["events"][0]["kind"], json!("note"));
    assert_eq!(ix["today"]["entries"][0]["text"], json!("Zed ausprobiert"));
    if env.has_git {
        // rebuilt after the autocommit: the work tree is clean
        assert_eq!(
            ix["logbook"]["git"]["dirty"],
            json!(false),
            "{}",
            ix["logbook"]
        );
        assert!(ix["logbook"]["git"]["head"].is_string());
    }

    let steps: [&[&str]; 5] = [
        &["plan", "new", "--", "Zed"],
        &["plan", "start", "C-2026-001"],
        &["event", "theme", "theme-set", "--subject", "kanagawa"],
        &["decide", "--no-edit", "--", "Zed statt VS Code"],
        &["plan", "verify", "C-2026-001"],
    ];
    for (i, args) in steps.iter().enumerate() {
        let now = format!("2026-10-01T17:1{i}:00+02:00");
        let out = env.at(&now, args);
        assert_eq!(
            out.status.code(),
            Some(0),
            "{args:?}: {}",
            common::stderr(&out)
        );
        assert_eq!(
            index(&env)["generatedAt"],
            json!(now),
            "{args:?} rebuilt the index"
        );
    }
    let ix = index(&env);
    common::assert_valid_index(&ix);
    assert_eq!(ix["cases"]["verification"][0]["id"], json!("C-2026-001"));
    assert_eq!(ix["decisions"][0]["id"], json!("ADR-0001"));
    assert_eq!(ix["drift"][0]["subject"], json!("kanagawa"));
    assert_eq!(ix["summary"]["openDrift"], json!(1));

    let out = env.at(
        "2026-10-01T17:30:00+02:00",
        &["capture", "--source", "theme"],
    );
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    assert_eq!(
        index(&env)["generatedAt"],
        json!("2026-10-01T17:30:00+02:00")
    );
    let _ = root;
}

#[test]
fn a_broken_case_file_is_skipped_with_a_warning() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    std::fs::write(
        root.join("work/queued/C-2026-009-broken.md"),
        "---\nid: nope\n---\n",
    )
    .unwrap();
    let out = env.at(NOW, &["index", "--check", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let json = common::json(&out);
    let warnings = json["warnings"].as_array().unwrap();
    assert_eq!(warnings.len(), 1, "{json}");
    assert!(
        warnings[0]
            .as_str()
            .unwrap()
            .starts_with("work/queued/C-2026-009-broken.md: ")
    );
    assert_eq!(index(&env)["cases"]["queued"], json!([]));
}
