//! `seldon status` (WP-007): STATUS.md with the generated header, user
//! text outside the fence kept, prose in the logbook language, no rewrite
//! when nothing changed; and the index rebuilt by the writing commands
//! (CONTRACT.md rule 2). Everything runs in a temp home (common::Env).

mod common;

use std::path::Path;

use serde_json::{Value, json};

use common::{Env, Snapper, copy_dir, fixture_logbook, read};

const HEADER: &str = "<!-- generated by seldon; do not edit -->";
const NOW: &str = "2026-10-01T17:05:12+02:00";

fn index(env: &Env) -> Value {
    serde_json::from_str(&read(&env.home.join(".local/state/seldon/index.json"))).unwrap()
}

fn status(env: &Env, now: &str) -> Value {
    let out = env.at(now, &["status", "--json"]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}{}",
        common::stdout(&out),
        common::stderr(&out)
    );
    common::json(&out)
}

fn git_log(env: &Env, root: &Path) -> String {
    common::stdout(&env.git(root, &["log", "--format=%s"]))
}

#[test]
fn status_writes_status_md_and_keeps_user_text() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let path = root.join("STATUS.md");
    assert!(read(&path).contains("No status yet"), "the init template");

    let out = status(&env, NOW);
    assert_eq!(out["ok"], json!(true));
    assert_eq!(out["status"], json!("STATUS.md"));
    assert!(
        out["files"]
            .as_array()
            .unwrap()
            .contains(&json!("STATUS.md")),
        "{out}"
    );
    assert_eq!(out["summary"]["activeCases"], json!(0));
    let text = read(&path);
    assert!(text.starts_with(&format!("{HEADER}\n<!-- seldon:begin status -->\n")));
    assert!(text.contains("\n## Overview\n- Active cases: 0 · in verification: 0 · queued: 0\n"));
    assert!(text.contains("## Open drift\n- none\n"));
    assert!(!text.contains("No status yet"), "the template is replaced");
    common::assert_valid_index(&index(&env));

    // the user writes above and below the fence
    let edited = text.replacen(
        "<!-- seldon:begin status -->",
        "My intro.\n\n<!-- seldon:begin status -->",
        1,
    ) + "\n## My notes\nKeep this.\n";
    std::fs::write(&path, &edited).unwrap();
    // a case changes the generated part
    let new = env.at(
        NOW,
        &["plan", "new", "--zone", "red", "--risk", "R2", "--", "Zed"],
    );
    assert_eq!(new.status.code(), Some(0), "{}", common::stderr(&new));
    let out = status(&env, NOW);
    let text = read(&path);
    assert!(text.starts_with(&format!(
        "{HEADER}\nMy intro.\n\n<!-- seldon:begin status -->\n"
    )));
    assert!(
        text.ends_with("<!-- seldon:end -->\n\n## My notes\nKeep this.\n"),
        "{text}"
    );
    assert!(
        text.contains("## Queued\n- [[C-2026-001]] Zed — red/R2"),
        "{text}"
    );
    assert!(text.contains("queued: 1"));
    assert_eq!(out["summary"]["queuedCases"], json!(1));
    assert_eq!(text.matches("seldon:begin status").count(), 1);

    // nothing changed: nothing is written, nothing committed
    let again = status(&env, "2026-10-01T18:00:00+02:00");
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(again["git"]["committed"], json!(false));
    assert_eq!(read(&path), text);
    if env.has_git {
        let log = git_log(&env, &root);
        assert_eq!(log.lines().next(), Some("seldon: status"), "{log}");
        assert_eq!(log.matches("seldon: status").count(), 2, "{log}");
    }
}

#[test]
fn status_prose_follows_the_logbook_language() {
    let env = Env::new(Snapper::Missing);
    let lb = env.tmp.path().join("logbook");
    copy_dir(&fixture_logbook(), &lb);
    let out = env.at(
        NOW,
        &["--logbook", lb.to_str().unwrap(), "status", "--json"],
    );
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let json = common::json(&out);
    assert_eq!(json["summary"]["openDrift"], json!(6));
    assert_eq!(json["git"]["committed"], json!(false), "no repository");
    let text = read(&lb.join("STATUS.md"));
    let generated = "\
<!-- generated by seldon; do not edit -->
<!-- seldon:begin status -->
# Status — workstation-7f3a

Stand: 2026-10-01 · letztes Ereignis 17:00 · Omarchy 4.0.7-1 · Theme tokyo-night

## Overview
- Aktive Cases: 2 · in Prüfung: 1 · geplant: 3
- Offene Drift: 6, davon Krise: 2
- Ereignisse heute: 32 · letzte 7 Tage: 53

## Active cases
- [[C-2026-003]] Omarchy auf 4.0.7 aktualisieren — red/R3 — 4/5 Schritte — agent:claude-code
- [[C-2026-004]] Zed als zweiten Editor installieren — red/R2 — 2/4 Schritte — agent:claude-code

## In verification
- [[C-2026-008]] Tailscale für Fernzugriff einrichten — red/R2 — 3/4 Schritte

## Queued
- [[C-2026-005]] Theme-Wechsel auf Tokyo Night durchziehen (Zed, Neovim) — yellow/R1 — 0/4 Schritte
- [[C-2026-006]] Snapper-Retention auf 14 Tage — red/R2 — 0/3 Schritte
- [[C-2026-007]] Herdr-Orchestrator als Default-Agent registrieren — yellow/R1 — 0/5 Schritte

## Open drift
- 15:30 theme · theme-set `tokyo-night` kanagawa → tokyo-night · human · Vorschlag [[C-2026-005]]
- **Krise** 14:03 config · config-add `~/.config/systemd/user/ollama.service` · agent:codex
- 14:02 pacman · install `ollama` 0.6.1-1 · agent:codex
- **Krise** 2026-09-29 20:45 config · config-add `~/.config/omarchy/hooks/post-update.d/backup-dotfiles.sh`
- 2026-09-28 13:20 config · config-remove `~/.config/hypr/monitors.conf`
- 2026-09-27 12:30 pacman · downgrade `mesa` 1:26.2.0-2 → 1:26.1.0-1 · 3 Ereignisse in dieser Transaktion
<!-- seldon:end -->
";
    assert_eq!(text, generated);
}

#[test]
fn a_degraded_collector_is_listed() {
    let env = Env::new(Snapper::NoPermissions);
    env.init_logbook();
    let out = env.at(NOW, &["capture", "--source", "snapper", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    status(&env, NOW);
    let root = env.tmp.path().join("logbook");
    let text = read(&root.join("STATUS.md"));
    assert!(
        text.contains("\n## Collectors\n- snapper: degraded — "),
        "{text}"
    );
    let ix = index(&env);
    let snapper = &ix["state"]["collectors"][1];
    assert_eq!(snapper["name"], json!("snapper"));
    assert_eq!(snapper["ok"], json!(false));
    assert!(
        snapper["message"]
            .as_str()
            .unwrap()
            .contains("No permissions")
    );
    assert!(snapper["lastRun"].is_string());
    assert_eq!(ix["state"]["lastCapture"], snapper["lastRun"]);
    assert_eq!(
        ix["state"]["collectors"][0]["lastRun"],
        json!(null),
        "pacman did not run"
    );
}

#[test]
fn writing_commands_rebuild_the_index() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let index_file = env.home.join(".local/state/seldon/index.json");
    assert!(!index_file.exists(), "init does not write the index");

    let log = env.at(NOW, &["log", "--", "Zed ausprobiert"]);
    assert_eq!(log.status.code(), Some(0), "{}", common::stderr(&log));
    assert!(common::stderr(&log).is_empty(), "{}", common::stderr(&log));
    let ix = index(&env);
    common::assert_valid_index(&ix);
    assert_eq!(ix["generatedAt"], json!(NOW));
    assert_eq!(ix["events"][0]["kind"], json!("note"));
    assert_eq!(ix["today"]["entries"][0]["text"], json!("Zed ausprobiert"));
    if env.has_git {
        // rebuilt after the autocommit: the work tree is clean
        assert_eq!(
            ix["logbook"]["git"]["dirty"],
            json!(false),
            "{}",
            ix["logbook"]
        );
        assert!(ix["logbook"]["git"]["head"].is_string());
    }

    let steps: [&[&str]; 5] = [
        &["plan", "new", "--", "Zed"],
        &["plan", "start", "C-2026-001"],
        &[
            "event",
            "plugins",
            "plugin-add",
            "--subject",
            "io.github.example.kanagawa",
        ],
        &["decide", "--no-edit", "--", "Zed statt VS Code"],
        &["plan", "verify", "C-2026-001"],
    ];
    for (i, args) in steps.iter().enumerate() {
        let now = format!("2026-10-01T17:1{i}:00+02:00");
        let out = env.at(&now, args);
        assert_eq!(
            out.status.code(),
            Some(0),
            "{args:?}: {}",
            common::stderr(&out)
        );
        assert_eq!(
            index(&env)["generatedAt"],
            json!(now),
            "{args:?} rebuilt the index"
        );
    }
    let ix = index(&env);
    common::assert_valid_index(&ix);
    assert_eq!(ix["cases"]["verification"][0]["id"], json!("C-2026-001"));
    assert_eq!(ix["decisions"][0]["id"], json!("ADR-0001"));
    assert_eq!(
        ix["drift"][0]["subject"],
        json!("io.github.example.kanagawa")
    );
    assert_eq!(ix["summary"]["openDrift"], json!(1));

    let out = env.at(
        "2026-10-01T17:30:00+02:00",
        &["capture", "--source", "theme"],
    );
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    assert_eq!(
        index(&env)["generatedAt"],
        json!("2026-10-01T17:30:00+02:00")
    );
    let _ = root;
}

#[test]
fn a_broken_case_file_is_skipped_with_a_warning() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    std::fs::write(
        root.join("work/queued/C-2026-009-broken.md"),
        "---\nid: nope\n---\n",
    )
    .unwrap();
    let out = env.at(NOW, &["index", "--check", "--json"]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let json = common::json(&out);
    let warnings = json["warnings"].as_array().unwrap();
    assert_eq!(warnings.len(), 1, "{json}");
    assert!(
        warnings[0]
            .as_str()
            .unwrap()
            .starts_with("work/queued/C-2026-009-broken.md: ")
    );
    assert_eq!(index(&env)["cases"]["queued"], json!([]));
}

#[test]
fn the_fast_rebuild_reads_head_without_git() {
    let env = Env::new(Snapper::Missing);
    if !env.has_git {
        eprintln!("skipped: no git on this host");
        return;
    }
    let root = env.init_logbook();
    let short = |env: &Env| {
        common::stdout(&env.git(&root, &["rev-parse", "--short=7", "HEAD"]))
            .trim()
            .to_string()
    };
    let head = |root: &Path| seldon::index::git_head_fast(root).unwrap().head.unwrap();
    // loose ref
    assert_eq!(head(&root), short(&env));
    // packed ref, and a detached HEAD
    assert!(env.git(&root, &["pack-refs", "--all"]).status.success());
    assert_eq!(head(&root), short(&env));
    assert!(
        env.git(&root, &["checkout", "-q", "--detach"])
            .status
            .success()
    );
    assert_eq!(head(&root), short(&env));
    assert!(seldon::index::git_head_fast(&env.tmp.path().join("nothing")).is_none());

    // the fast rebuild writes `head` and leaves `dirty` out
    let dirs = seldon::config::Dirs {
        home: env.home.clone(),
        xdg_config_home: env.home.join(".config"),
        state_dir: env.home.join(".local/state/seldon"),
    };
    let ctx = seldon::commands::Context {
        dirs,
        json: false,
        quiet: false,
        no_commit: false,
        logbook_flag: Some(root.clone()),
        logbook_env: None,
        config_file: env.config_file(),
        now: chrono::DateTime::parse_from_rfc3339(NOW).unwrap(),
    };
    seldon::index::rebuild_if_initialised_fast(&ctx);
    let ix = index(&env);
    common::assert_valid_index(&ix);
    assert_eq!(ix["generatedAt"], json!(NOW));
    assert_eq!(ix["logbook"]["git"], json!({ "head": short(&env) }));
}

/// WP-050: `decide` and `status` fill the `decisions.index` fence of
/// DECISIONS.md from decisions/*.md; text outside it is the user's.
#[test]
fn decide_and_status_fill_the_decisions_index() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let path = root.join("DECISIONS.md");
    let template = read(&path);
    assert!(template.contains("Seldon fills the table between the fences"));
    // the user writes above and below the fence
    let mine = template.replacen(
        "<!-- seldon:begin decisions.index -->",
        "My intro.\n\n<!-- seldon:begin decisions.index -->",
        1,
    ) + "\n## Notes\nKeep this.\n";
    std::fs::write(&path, &mine).unwrap();

    for title in ["First", "Pipes | in titles"] {
        let out = env.at(NOW, &["decide", "--no-edit", "--json", "--", title]);
        assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
        assert_eq!(common::json(&out)["warnings"], json!([]));
    }
    let rows = "\
<!-- seldon:begin decisions.index -->
| ID | Title | Status | Date |
|---|---|---|---|
| [[ADR-0002]] | Pipes \\| in titles | proposed | 2026-10-01 |
| [[ADR-0001]] | First | proposed | 2026-10-01 |
<!-- seldon:end -->
";
    let text = read(&path);
    assert!(
        text.contains(&format!("My intro.\n\n{rows}\n## Notes\nKeep this.\n")),
        "{text}"
    );
    assert!(text.ends_with("\n## Notes\nKeep this.\n"));
    if env.has_git {
        // in the decision's own commit
        let files =
            common::stdout(&env.git(&root, &["show", "--name-only", "--format=%s", "HEAD"]));
        assert!(files.starts_with("seldon: ADR-0002 proposed\n"), "{files}");
        assert!(files.contains("\nDECISIONS.md\n"), "{files}");
    }

    // nothing new: status writes nothing
    let out = status(&env, NOW);
    assert!(
        !out["files"]
            .as_array()
            .unwrap()
            .contains(&json!("DECISIONS.md")),
        "{out}"
    );
    assert_eq!(read(&path), text);

    // the human accepts ADR-0001 in its file; status picks it up
    let adr = root.join("decisions/ADR-0001-first.md");
    std::fs::write(
        &adr,
        read(&adr).replace("status: proposed", "status: accepted"),
    )
    .unwrap();
    // a translated table head stays
    std::fs::write(
        &path,
        text.replace(
            "| ID | Title | Status | Date |",
            "| ID | Titel | Status | Datum |",
        ),
    )
    .unwrap();
    let out = status(&env, NOW);
    assert!(
        out["files"]
            .as_array()
            .unwrap()
            .contains(&json!("DECISIONS.md")),
        "{out}"
    );
    let filled = read(&path);
    assert!(filled.contains("| ID | Titel | Status | Datum |\n|---|---|---|---|\n| [[ADR-0002]]"));
    assert!(filled.contains("| [[ADR-0001]] | First | accepted | 2026-10-01 |\n"));
    // the second run writes nothing
    let again = status(&env, "2026-10-01T18:00:00+02:00");
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(read(&path), filled);

    // a fence without its end is left alone, with a warning
    let broken = filled.replace("<!-- seldon:end -->\n", "");
    std::fs::write(&path, &broken).unwrap();
    let out = status(&env, NOW);
    let warnings = out["warnings"].as_array().unwrap();
    assert!(
        warnings.iter().any(|w| w
            .as_str()
            .unwrap()
            .contains("decisions.index fence has no end")),
        "{out}"
    );
    assert_eq!(read(&path), broken);

    // a file without the fence gets it appended; a missing file is created
    std::fs::write(&path, "# Mine\nNo table.").unwrap();
    status(&env, NOW);
    let appended = read(&path);
    assert!(
        appended.starts_with(
            "# Mine\nNo table.\n\n## Index\n\n<!-- seldon:begin decisions.index -->\n| ID | Title |"
        ),
        "{appended}"
    );
    std::fs::remove_file(&path).unwrap();
    status(&env, NOW);
    assert!(read(&path).starts_with("# Decisions\n\n<!-- seldon:begin decisions.index -->\n"));
}

/// The fixture's hand-made table is what the engine writes: no change.
#[test]
fn the_fixture_decisions_index_is_stable() {
    let env = Env::new(Snapper::Missing);
    let lb = env.tmp.path().join("logbook");
    copy_dir(&fixture_logbook(), &lb);
    let out = env.at(
        NOW,
        &["--logbook", lb.to_str().unwrap(), "status", "--json"],
    );
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let v = common::json(&out);
    assert!(
        !v["files"]
            .as_array()
            .unwrap()
            .contains(&json!("DECISIONS.md")),
        "{v}"
    );
    assert_eq!(
        read(&lb.join("DECISIONS.md")),
        read(&fixture_logbook().join("DECISIONS.md"))
    );
}

/// An invalid decision file is skipped by the fill and named in
/// `decide --json`'s warnings; the new decision is still created.
#[test]
fn decide_names_a_skipped_decision_in_its_warnings() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    std::fs::write(
        root.join("decisions/ADR-0001-broken.md"),
        "---\nid: nope\n---\n",
    )
    .unwrap();
    let out = env.at(NOW, &["decide", "--no-edit", "--json", "--", "Good"]);
    assert_eq!(out.status.code(), Some(0), "{}", common::stderr(&out));
    let v = common::json(&out);
    assert_eq!(v["decision"]["id"], "ADR-0002");
    let warnings = v["warnings"].as_array().unwrap();
    assert_eq!(warnings.len(), 1, "{v}");
    let w = warnings[0].as_str().unwrap();
    assert!(w.starts_with("decisions/ADR-0001-broken.md: "), "{w}");
    assert!(w.ends_with("; skipped"), "{w}");
    let text = read(&root.join("DECISIONS.md"));
    assert!(
        text.contains("| [[ADR-0002]] | Good | proposed |"),
        "{text}"
    );
    assert!(!text.contains("ADR-0001"), "{text}");
    // the human output carries it too
    let out = env.at(NOW, &["decide", "--no-edit", "--", "Another"]);
    assert!(
        common::stdout(&out).contains("\nwarning: decisions/ADR-0001-broken.md: "),
        "{}",
        common::stdout(&out)
    );
}

fn ok(env: &Env, args: &[&str]) {
    let out = env.at(NOW, args);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{args:?}: {}",
        common::stderr(&out)
    );
}

/// F-130: a fence end marker in a case title and in a decision title stays
/// inside its fence; STATUS.md and DECISIONS.md keep their size and
/// `status` stops committing.
#[test]
fn a_fence_marker_in_a_title_stays_in_its_fence() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let title = "Document the <!-- seldon:end --> marker";
    ok(
        &env,
        &[
            "plan", "new", "--zone", "green", "--risk", "R0", "--", title,
        ],
    );
    ok(&env, &["plan", "start", "C-2026-001"]);
    ok(
        &env,
        &[
            "decide",
            "--no-edit",
            "--",
            "Keep the <!-- seldon:begin status --> marker literal",
        ],
    );
    let files = [root.join("STATUS.md"), root.join("DECISIONS.md")];
    let mut runs = Vec::new();
    for _ in 0..3 {
        status(&env, NOW);
        runs.push(files.iter().map(|f| read(f)).collect::<Vec<_>>());
    }
    let sizes: Vec<Vec<usize>> = runs
        .iter()
        .map(|r| r.iter().map(String::len).collect())
        .collect();
    assert_eq!(sizes[0], sizes[1], "{sizes:?}");
    assert_eq!(sizes[1], sizes[2], "{sizes:?}");
    assert_eq!(runs[0], runs[2]);
    let (status_md, decisions_md) = (&runs[2][0], &runs[2][1]);
    assert!(
        status_md.contains("Document the <!--\u{200B} seldon:end --> marker"),
        "{status_md}"
    );
    assert!(
        decisions_md.contains("Keep the <!--\u{200B} seldon:begin status --> marker literal"),
        "{decisions_md}"
    );
    for text in [status_md, decisions_md] {
        assert_eq!(text.matches("<!-- seldon:end -->").count(), 1, "{text}");
        assert_eq!(text.matches("<!-- seldon:begin ").count(), 1, "{text}");
    }
    if env.has_git {
        let log = git_log(&env, &root);
        assert_eq!(
            log.lines().filter(|l| *l == "seldon: status").count(),
            1,
            "{log}"
        );
    }
}

/// F-131: a STATUS.md whose marker lines were edited away is left alone
/// with a warning, the user's lines kept; a CRLF STATUS.md merges.
#[test]
fn a_damaged_status_md_is_left_alone() {
    let env = Env::new(Snapper::Missing);
    let root = env.init_logbook();
    let path = root.join("STATUS.md");
    status(&env, NOW);
    let notes = read(&path) + "\n## My notes\nKeep this.\n";
    ok(&env, &["plan", "new", "--", "Zed"]);

    for damaged in [
        notes.replace("<!-- seldon:end -->\n", ""),
        notes.replace("<!-- seldon:begin status -->\n", ""),
        // end marker gone, a complete begin…end block pasted below
        notes.replace("<!-- seldon:end -->\n", "")
            + "\n<!-- seldon:begin status -->\npasted\n<!-- seldon:end -->\n",
    ] {
        std::fs::write(&path, &damaged).unwrap();
        let out = status(&env, NOW);
        let warnings = out["warnings"].as_array().unwrap();
        assert!(
            warnings
                .iter()
                .any(|w| w.as_str().unwrap().starts_with("STATUS.md: ")
                    && w.as_str().unwrap().contains("file not updated")),
            "{out}"
        );
        assert!(
            !out["files"]
                .as_array()
                .unwrap()
                .contains(&json!("STATUS.md"))
        );
        assert_eq!(std::fs::read(&path).unwrap(), damaged.as_bytes());
    }

    // CRLF: the fence is found, the new body gets CRLF, the notes stay
    std::fs::write(&path, notes.replace('\n', "\r\n")).unwrap();
    let out = status(&env, NOW);
    assert_eq!(out["warnings"], json!([]), "{out}");
    assert!(
        out["files"]
            .as_array()
            .unwrap()
            .contains(&json!("STATUS.md"))
    );
    let text = read(&path);
    assert!(text.contains("[[C-2026-001]] Zed"), "{text}");
    assert!(
        text.ends_with("\r\n\r\n## My notes\r\nKeep this.\r\n"),
        "{text}"
    );
    assert!(
        !text.replace("\r\n", "").contains('\n'),
        "only CRLF: {text:?}"
    );
    assert_eq!(text.matches("<!-- seldon:begin status -->").count(), 1);
    let again = status(&env, NOW);
    assert_eq!(again["files"], json!([]), "{again}");
    assert_eq!(read(&path), text);
}
