#!/usr/bin/env python3
"""Render the guard's expectation table for review (WP-130).

Runs scripts/guard-test.sh with GUARD_TEST_REPORT, so every row shows the
verdict and message of the guard as it is, and writes a Markdown table:
allowed rows first, then blocked rows, each grouped by the table's
sections, followed by the "Known limits" section of a handover, verbatim.

    python3 scripts/guard-table.py OUT.md [--limits HANDOVER.md]
    python3 scripts/guard-table.py --check OUT.md [--limits HANDOVER.md]

--check regenerates and fails when OUT.md differs (the table drifted).
"""

import html
import json
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HEADER = "<!-- generated by scripts/guard-table.py from scripts/guard-test.sh; do not edit -->"


def run_table():
    with tempfile.TemporaryDirectory(prefix="guard-table.") as tmp:
        report = os.path.join(tmp, "rows.jsonl")
        env = dict(os.environ, GUARD_TEST_REPORT=report, GUARD_TEST_QUIET="1")
        env.pop("GUARD_SH", None)
        run = subprocess.run(["bash", os.path.join(HERE, "guard-test.sh")], env=env, capture_output=True, text=True)
        if run.returncode != 0:
            sys.exit(f"guard-test.sh is not green:\n{run.stdout}{run.stderr}")
        with open(report, encoding="utf-8") as f:
            return [json.loads(line) for line in f]


def known_limits(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    start = next((i for i, line in enumerate(lines) if line.startswith("## Known limits")), None)
    if start is None:
        sys.exit(f"{path}: no '## Known limits' section")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    return "\n".join(lines[start + 1:end]).strip()


def cell(text):
    """Text for a table cell: HTML-escaped, newlines visible, pipes safe."""
    return html.escape(text).replace("|", "&#124;").replace("\n", "<br>")


def reason(row):
    msg = row["reason"].strip()
    if row["got"] == "A":
        return "allowed"
    for prefix, short in (("guard: blocked (AGENTS.md §6 red zone): ", "red zone: "),
                          ("guard: blocked (fail closed, cannot check this command): ", "fail closed: ")):
        if msg.startswith(prefix):
            return short + msg[len(prefix):]
    return msg


def render(rows, limits):
    allowed = [r for r in rows if r["want"] == "A"]
    blocked = [r for r in rows if r["want"] == "B"]
    out = [HEADER, "", "# WP-130 — the guard's test table", "",
           f"{len(rows)} rows of `scripts/guard-test.sh`: {len(allowed)} allowed, {len(blocked)} blocked. "
           "Each row is the input (a command text; nothing is executed), the verdict, and the guard's own "
           "message for it. Allowed rows first, then blocked rows, both grouped by the table's sections. "
           "The rows run with a fake HOME `/home/tester` and working directory `/home/tester/repo`; "
           "a context in brackets names a row's test setting.", "",
           "What the guard does not protect is listed under [Known limits](#known-limits) at the end.", ""]
    for title, part in (("Allowed", allowed), ("Blocked", blocked)):
        out += [f"## {title}", ""]
        sections = []
        for r in part:
            if r["section"] not in sections:
                sections.append(r["section"])
        for sec in sections:
            out += [f"### {sec}", "", "| Input | Verdict | Reason |", "|---|---|---|"]
            for r in (r for r in part if r["section"] == sec):
                ctx = f" [{r['context']}]" if r["context"] else ""
                out.append(f"| <code>{cell(r['input'])}</code>{cell(ctx)} | {'allow' if r['got'] == 'A' else 'block'} "
                           f"| {cell(reason(r))} |")
            out.append("")
    out += ["## Known limits", "", limits, ""]
    return "\n".join(out)


def main():
    args = sys.argv[1:]
    check = "--check" in args
    if check:
        args.remove("--check")
    limits_file = os.path.join(ROOT, "work", "active", "WP-130", "HANDOVER.md")
    if "--limits" in args:
        k = args.index("--limits")
        limits_file = args[k + 1]
        del args[k:k + 2]
    if len(args) != 1:
        sys.exit(__doc__)
    text = render(run_table(), known_limits(limits_file))
    if check:
        if open(args[0], encoding="utf-8").read() != text:
            sys.exit(f"{args[0]} is out of date: run python3 scripts/guard-table.py {args[0]}")
        print(f"{args[0]}: up to date")
        return 0
    with open(args[0], "w", encoding="utf-8") as f:
        f.write(text)
    print(f"{args[0]}: {text.count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
