//! `seldon` — the Seldon engine (SPEC-ENGINE.md).
//!
//! The binary (`src/main.rs`) is a thin CLI over this library so that the
//! integration tests in `tests/` can use the types directly.

pub mod attribution;
pub mod case_notes;
pub mod collectors;
pub mod commands;
pub mod config;
pub mod config_scan;
pub mod dossier;
pub mod error;
pub mod frontmatter;
pub mod import;
pub mod index;
pub mod ledger;
pub mod logbook;
pub mod model;
pub mod pkgcmd;
pub mod rebuild;
pub mod reconcile;
pub mod redact;
pub mod sessions;
pub mod sys;

/// Engine version: Cargo.toml's, plus `+<build>` when the build set
/// `SELDON_BUILD` (the test host's builds from main: `0.1.3+main.1a2b3c4`,
/// WP-098). Release builds leave it unset and stay plain. A value that is
/// not semver build metadata fails the build.
pub const VERSION: &str = match std::str::from_utf8(&VERSION_BYTES) {
    Ok(v) => v,
    Err(_) => panic!("VERSION is not UTF-8"),
};

const BUILD: &str = match option_env!("SELDON_BUILD") {
    Some(b) => b,
    None => "",
};
const VERSION_LEN: usize = version_len(env!("CARGO_PKG_VERSION"), BUILD);
const VERSION_BYTES: [u8; VERSION_LEN] = version_bytes(env!("CARGO_PKG_VERSION"), BUILD);

/// True when `build` is semver build metadata: dot-separated, non-empty
/// identifiers of `[0-9A-Za-z-]`.
const fn build_metadata_ok(build: &str) -> bool {
    let b = build.as_bytes();
    if b.is_empty() || b[0] == b'.' || b[b.len() - 1] == b'.' {
        return false;
    }
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        let dot_after_dot = c == b'.' && b[i - 1] == b'.';
        if dot_after_dot || !(c.is_ascii_alphanumeric() || c == b'-' || c == b'.') {
            return false;
        }
        i += 1;
    }
    true
}

/// Length of `version_bytes(pkg, build)`.
const fn version_len(pkg: &str, build: &str) -> usize {
    if build.is_empty() {
        pkg.len()
    } else {
        pkg.len() + 1 + build.len()
    }
}

/// `pkg`, or `pkg+build` when `build` is not empty; panics (a build error
/// in a const) when `build` is not semver build metadata.
const fn version_bytes<const N: usize>(pkg: &str, build: &str) -> [u8; N] {
    assert!(
        build.is_empty() || build_metadata_ok(build),
        "SELDON_BUILD must be semver build metadata: dot-separated [0-9A-Za-z-] identifiers"
    );
    assert!(
        N == version_len(pkg, build),
        "N must be version_len(pkg, build)"
    );
    let mut out = [0u8; N];
    let (p, b) = (pkg.as_bytes(), build.as_bytes());
    let mut i = 0;
    while i < p.len() {
        out[i] = p[i];
        i += 1;
    }
    if !b.is_empty() {
        out[i] = b'+';
        let mut j = 0;
        while j < b.len() {
            out[i + 1 + j] = b[j];
            j += 1;
        }
    }
    out
}

/// The contract version this engine writes (`index.json.contractVersion`).
/// Must equal `manifest.json.seldon.contractVersion` (docs/CONTRACT.md).
pub const CONTRACT_VERSION: u32 = 2;

/// The oldest plugin contract that reads this engine's index without
/// misreading a field it keys on (`index.json.contractReadableFrom`,
/// ADR-0051). Lower than `CONTRACT_VERSION` only when the ADR of that bump
/// lists, per field, why an older reader does not misread.
pub const CONTRACT_READABLE_FROM: u32 = 2;
const _: () = assert!(CONTRACT_READABLE_FROM >= 1 && CONTRACT_READABLE_FROM <= CONTRACT_VERSION);

/// First line of every file the engine generates (AGENTS.md §7).
pub const GENERATED_HEADER: &str = "<!-- generated by seldon; do not edit -->";

#[cfg(test)]
mod tests {
    use super::*;

    // Both forms through the same const fns VERSION uses (WP-098).
    const PLAIN: [u8; version_len("0.1.3", "")] = version_bytes("0.1.3", "");
    const MARKED: [u8; version_len("0.1.3", "main.1a2b3c4")] =
        version_bytes("0.1.3", "main.1a2b3c4");

    #[test]
    fn a_release_build_is_plain_and_a_main_build_carries_the_marker() {
        assert_eq!(std::str::from_utf8(&PLAIN).unwrap(), "0.1.3");
        assert_eq!(std::str::from_utf8(&MARKED).unwrap(), "0.1.3+main.1a2b3c4");
    }

    #[test]
    fn this_build_is_the_crate_version_plus_seldon_build() {
        match option_env!("SELDON_BUILD") {
            Some(b) if !b.is_empty() => {
                assert_eq!(VERSION, format!("{}+{b}", env!("CARGO_PKG_VERSION")))
            }
            _ => assert_eq!(VERSION, env!("CARGO_PKG_VERSION")),
        }
    }

    #[test]
    fn only_semver_build_metadata_is_accepted() {
        for ok in ["main.1a2b3c4", "a", "x-y.0.Z9", "main.0000000"] {
            assert!(build_metadata_ok(ok), "{ok}");
        }
        for bad in [
            "",
            ".",
            "main.",
            ".main",
            "main..abc",
            "main abc",
            "main+abc",
            "main/abc",
            "mäin",
            "main_abc",
            "\n",
        ] {
            assert!(!build_metadata_ok(bad), "{bad:?}");
        }
    }

    #[test]
    #[should_panic(expected = "SELDON_BUILD must be semver build metadata")]
    fn a_bad_marker_is_refused() {
        let _: [u8; 11] = version_bytes("0.1.3", "a b");
    }
}
