//! `seldon` — the Seldon engine (SPEC-ENGINE.md).
//!
//! The binary (`src/main.rs`) is a thin CLI over this library so that the
//! integration tests in `tests/` can use the types directly.

pub mod attribution;
pub mod collectors;
pub mod commands;
pub mod config;
pub mod error;
pub mod frontmatter;
pub mod index;
pub mod ledger;
pub mod logbook;
pub mod model;
pub mod pkgcmd;
pub mod reconcile;
pub mod redact;
pub mod sys;

/// Engine version, from Cargo.toml.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The contract version this engine writes (`index.json.contractVersion`).
/// Must equal `manifest.json.seldon.contractVersion` (docs/CONTRACT.md).
pub const CONTRACT_VERSION: u32 = 1;

/// First line of every file the engine generates (AGENTS.md §7).
pub const GENERATED_HEADER: &str = "<!-- generated by seldon; do not edit -->";
